apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  labels:
    app: ml-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model-container
        image: developementRegistry.azurecr.io/ml-model:latest
        ports:
        - containerPort: 5000
--- 
apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
  labels:
    app: ml-model
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: ml-model
