name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Validate Dataset Format
      run: |
          if ! ls data/*.csv; then
            echo "Error: No CSV files found in the 'data/' directory!"
            exit 1
          fi

    - name: Preprocess Dataset
      run: |
        python src/preprocess.py
    
    - name: Train Model Incrementally
      run: |
        python src/train.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: model/trained_model.pkl


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Model Artifact
      uses: actions/download-artifact@v3
      with:
        name: trained-model
        path: model/

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
          registry: "developementRegistry.azurecr.io"
          username: "developementRegistry"
          password: "sE9bTqDyjWHmOrKaz0CWsguprKdS2LulZBZSabKUIQ+ACRCp7q8v"

    - name: Build Docker Image
      run: |
        docker build -t devavaxiaregistry.azurecr.io/mlops-template/ml-model:latest .

    - name: Set up Docker Build
      run: | 
          docker build . -f ./Dockerfile -t developementRegistry.azurecr.io/ml-model:latest
                
    - name: Push Docker image-dev
      run: |
          docker push developementRegistry.azurecr.io/ml-model:latest

#### to add kustomize stage.